# Generated by Django 4.0.4 on 2022-06-08 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='urlobj',
            name='shortened_url',
        ),
    ]
